//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoRegion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статистика_
    {
        public int Код { get; set; }
        public int Регион { get; set; }
        public int Статья { get; set; }
        public int Год { get; set; }
        public double СуммаЗатрат { get; set; }
    
        public virtual Лета Лета { get; set; }
        public virtual Регион_ Регион_ { get; set; }
        public virtual Статья_ Статья_ { get; set; }
    }
}
